name: auth_app
description: Aplicativo de autenticação com Flutter, Firebase, Clean Arch, ValueNotifier e TDD.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 
  mocktail: ^0.3.0
  faker:
  firebase_auth: 
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.4
  ionicons: ^0.1.2
  overlay_support: ^2.0.0
  flutter_svg: ^1.1.0
  value_listenable_test: ^0.0.1
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
      - family: Gotham-SSm
        fonts:
          - asset: assets/fonts/Gotham-SSm/GothamSSm-XLight.ttf
            weight: 200
          - asset: assets/fonts/Gotham-SSm/GothamSSm-XLightItalic.ttf
            weight: 200
            style: italic

          - asset: assets/fonts/Gotham-SSm/GothamSSm-Light.ttf
            weight: 300
          - asset: assets/fonts/Gotham-SSm/GothamSSm-LightItalic.ttf
            weight: 300
            style: italic

          - asset: assets/fonts/Gotham-SSm/GothamSSm-Book.ttf
            weight: 400
          - asset: assets/fonts/Gotham-SSm/GothamSSm-BookItalic.ttf
            weight: 400
            style: italic

          - asset: assets/fonts/Gotham-SSm/GothamSSm-Medium.ttf
            weight: 500
          - asset: assets/fonts/Gotham-SSm/GothamSSm-MediumItalic.ttf
            weight: 500
            style: italic

          - asset: assets/fonts/Gotham-SSm/GothamSSm-Bold.ttf
            weight: 700
          - asset: assets/fonts/Gotham-SSm/GothamSSm-BoldItalic.ttf
            weight: 700
            style: italic

          - asset: assets/fonts/Gotham-SSm/GothamSSm-Black.ttf
            weight: 900
          - asset: assets/fonts/Gotham-SSm/GothamSSm-BlackItalic.ttf
            weight: 900
