// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiUScW1k1s0kHyIBzClJ93DRxTXJqiQ_Y',
    appId: '1:283509147750:web:98e76dc67523d89bff85a7',
    messagingSenderId: '283509147750',
    projectId: 'authdb-e98a6',
    authDomain: 'authdb-e98a6.firebaseapp.com',
    storageBucket: 'authdb-e98a6.appspot.com',
    measurementId: 'G-S2V52KR3L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-dxIqUCva3FHFwxIC91QaeAZBESNCeZ4',
    appId: '1:283509147750:android:d86fb3c9adfaf25bff85a7',
    messagingSenderId: '283509147750',
    projectId: 'authdb-e98a6',
    storageBucket: 'authdb-e98a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9gnffg7ZE3O9-zMsdYDjH1ycXEvtPpWk',
    appId: '1:283509147750:ios:339639087cb8b93eff85a7',
    messagingSenderId: '283509147750',
    projectId: 'authdb-e98a6',
    storageBucket: 'authdb-e98a6.appspot.com',
    iosClientId: '283509147750-oesu3u27d5vnm2jals0flfokmj3gc350.apps.googleusercontent.com',
    iosBundleId: 'com.viniciusmorais.authApp',
  );
}
